### ISSUE TITLE
How to work with fallbacks?

### ISSUE THREAD

**Issue by danielberndt** [seek-oss/treat#120]
Hello there:

I've got the following use case:

```css
.screenHeight {
  min-height: 100vh;
  min-height: -webkit-fill-available;
}
```

how do I do this using treat?

I was hoping this syntax I've seen for other css-in-js libs would work, but it seems like it didn't:

```js
const screenHeight = style({minHeight: ["100vh", "-webkit-fill-available"]});
```
