### ISSUE TITLE
Generated `globalStyle` selector contains dollar char, missing theme reference.

### ISSUE THREAD

**Issue by fenetic** [seek-oss/treat#150]
After reading [this issue](https://github.com/seek-oss/treat/issues/74), I am implementing the following `globalStyle` in `sweet-treat.treat.ts`:

```TypeScript
const sweetTreat = style((theme) => ({
  padding: `${theme.spacing.small}px`,
}));

globalStyle(`${sweetTreat} > *`, {
  color: 'red',
});
```

...Which produces something like:

```css
.sweet-treat-style_3zB1k_default-theme_nmFw > * {
    color: 'red';
}
```

...With the theme correctly appended to the class name... However, referencing a themed `styleMap`-generated class in `globalStyle` selector:

 ```TypeScript
const sweetTreat = styleMap((theme) => ({
  small: {
    padding: `${theme.spacing.small}px`,
  }
}));

globalStyle(`${sweetTreat.small} > *`, (theme) => ({
  color: theme.palette.error,
}));
```

...Generates a CSS class name with a dollar `$` prepended and the theme reference missing:

```css
$.sweet-treat-small_3oo5N > * {
    color: 'red';
}
```

I haven't had an extensive rummage but it looks like it's the `themePlaceholder` being used in [utils.ts](https://github.com/seek-oss/treat/blob/master/packages/treat/src/utils.ts#L5)?
