### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by lencioni** [seek-oss/treat#90]
I am considering adopting Treat for a project where having good automatic right-to-left support is important. I didn't see anything in the docs about this, or how Treat might be able to be extended to support this, so I'm opening this issue to kick off the conversation.

Do you see a good way to use/extend Treat to support auto RTL flipping, or to build that feature into Treat directly?

This is similar to [@jpnelson's question over on Linaria](https://github.com/callstack/linaria/issues/491):

> ## Describe the feature
> It would be nice to have some form of RTL support for the library. For example, you can see how [react native web](https://github.com/necolas/react-native-web/blob/master/docs/guides/style.md#implementation-details) handles this – the requirement is that there are different static styles compiled that can be switched between at runtime, particularly the LTR and RTL styles. https://github.com/kentcdodds/rtl-css-js is a library that does the actual "style flipping" logic.
> 
> ## Motivation
> We'd like to be able to support languages that have a RTL flow.
> 
> ## Related Issues
> I couldn't find any but let me know if this has been talked about before!
> 
> As a side note, I'm interested in whether this is something that you'd be open to PR's for. Thanks!

**Comment by mattsjones** [comment]
Hey 👋 

This is an interesting one. We had a chat internally about this and we're thinking we could add a simple (to start with) plugin API to treat for these kinds of issues. That way you could run something like `rtl-css-js` over your styles at build-time. Potentially this could be theme specific as well, would have to think this through further though. 

e.g.
```
new TreatPlugin({
  plugins: [rtl-plugin]
})
```

Thoughts?

**Comment by lencioni** [comment]
I think that could work.

However, I'm wondering if Treat could be composed with PostCSS in some way today e.g. via postcss-loader? If so, then I think it would work to handle the RTL and whatever other processing we need to do (e.g. autoprefixing) in PostCSS. Looking at the webpack example in the docs, it seems like this could be passed in to the outputLoaders option, something like this, right?

```js
const TreatPlugin = require('treat/webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const PostCSSLoader = require('postcss-loader');

module.exports = {
  plugins: [
    new TreatPlugin({
      outputLoaders: [MiniCssExtractPlugin.loader, PostCSSLoader]
    }),
    new MiniCssExtractPlugin()
  ]
};
```

**Comment by mattsjones** [comment]
We actually use PostCSS internally for [minification](https://seek-oss.github.io/treat/webpack-options#minify) and [autoprefixing](https://seek-oss.github.io/treat/webpack-options#browsers). We chose not to expose this functionality though as we can't guarantee the CSS output from treat will be correct when passed through various plugins. 

Also PostCSSLoader won't work as an outputLoader as it needs to run before css-loader. Is there any other use-cases you were thinking of?

Btw does your project require theming? And do you need to apply the RTL stuff differently per theme?

**Comment by lencioni** [comment]
> We actually use PostCSS internally for minification and autoprefixing. 
Gotcha, that makes sense.

> Also PostCSSLoader won't work as an outputLoader as it needs to run before css-loader. Is there any other use-cases you were thinking of?

I could imagine that some PostCSS plugins could be useful for adding more fallbacks for older browsers than what autoprefixer would, but I don't have any plugins specifically in mind at the moment.

> Btw does your project require theming? And do you need to apply the RTL stuff differently per theme?

Yes, this project needs theming. I don't think the RTL needs to be applied differently per theme.

**Comment by mattsjones** [comment]
Right. I'm open to exposing more hooks into the output CSS to allow customisations but I'm wary of being coupled to PostCSS long term. Atm its more of an implementation detail.

I'm surprised the RTL requirements are not theme specific. Is your plan to compile the app multiple times with different settings?

**Comment by lencioni** [comment]
> I'm surprised the RTL requirements are not theme specific. Is your plan to compile the app multiple times with different settings?

It's all about the selectors. Check out the [postcss-rtl readme](https://github.com/vkalinichev/postcss-rtl#simple-properties).

With this input:

```css
.foo {
    float: right;
    margin-left: 13px;
    text-align: right;
    font-size: 13px;
    border-color: lightgray;
    border-width: 2px 0 2px 2px;
    border-style: solid dashed solid solid
}

.foo {
    text-align: center;
}
```

it will be compiled into this output:

```css
.foo {
    font-size: 13px
}

[dir] .foo {
    border-color: lightgray
}

[dir="ltr"] .foo {
    float: right;
    margin-left: 13px;
    text-align: right;
    border-width: 2px 0 2px 2px;
    border-style: solid dashed solid solid
}

[dir="rtl"] .foo {
    float: left;
    margin-right: 13px;
    text-align: left;
    border-width: 2px 2px 2px 0;
    border-style: solid solid solid dashed
}

[dir] .foo {
    text-align: center
}
```

This allows you to control the direction at the HTML level by using `<div dir="rtl">...</div>` or whatever. So I think this should be able to run on everything and it will just work.
